/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...catchAll]': RouteRecordInfo<
      '/[...catchAll]',
      '/:catchAll(.*)',
      { catchAll: ParamValue<true> },
      { catchAll: ParamValue<false> },
      | never
    >,
    '/aerolineas/': RouteRecordInfo<
      '/aerolineas/',
      '/aerolineas',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/clientes/': RouteRecordInfo<
      '/clientes/',
      '/clientes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/': RouteRecordInfo<
      '/dashboard/',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/detalles/': RouteRecordInfo<
      '/detalles/',
      '/detalles',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/llegada/': RouteRecordInfo<
      '/llegada/',
      '/llegada',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/salida/': RouteRecordInfo<
      '/salida/',
      '/salida',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vuelos/': RouteRecordInfo<
      '/vuelos/',
      '/vuelos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/vuelos/[...catchAll]': RouteRecordInfo<
      '/vuelos/[...catchAll]',
      '/vuelos/:catchAll(.*)',
      { catchAll: ParamValue<true> },
      { catchAll: ParamValue<false> },
      | never
    >,
    '/vuelos/[id]': RouteRecordInfo<
      '/vuelos/[id]',
      '/vuelos/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/vuelos/catalogo': RouteRecordInfo<
      '/vuelos/catalogo',
      '/vuelos/catalogo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...catchAll].vue': {
      routes:
        | '/[...catchAll]'
      views:
        | never
    }
    'src/pages/aerolineas/index.vue': {
      routes:
        | '/aerolineas/'
      views:
        | never
    }
    'src/pages/clientes/index.vue': {
      routes:
        | '/clientes/'
      views:
        | never
    }
    'src/pages/dashboard/index.vue': {
      routes:
        | '/dashboard/'
      views:
        | never
    }
    'src/pages/detalles/index.vue': {
      routes:
        | '/detalles/'
      views:
        | never
    }
    'src/pages/llegada/index.vue': {
      routes:
        | '/llegada/'
      views:
        | never
    }
    'src/pages/salida/index.vue': {
      routes:
        | '/salida/'
      views:
        | never
    }
    'src/pages/vuelos/index.vue': {
      routes:
        | '/vuelos/'
      views:
        | never
    }
    'src/pages/vuelos/[...catchAll].vue': {
      routes:
        | '/vuelos/[...catchAll]'
      views:
        | never
    }
    'src/pages/vuelos/[id].vue': {
      routes:
        | '/vuelos/[id]'
      views:
        | never
    }
    'src/pages/vuelos/catalogo.vue': {
      routes:
        | '/vuelos/catalogo'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
